kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hw-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-4
  template:
    metadata:
      labels:
        app: hw-4
    spec:
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: rapid
          image: 'codefresh/rapid:master'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
